// Twelve kinds of site, each with complete starter words. People carve their own name in;
// everything here is only a starting point.
import type { Content } from './content';

export interface Kind {
  id: string;
  name: string;
  emoji: string;
  content: Content;
}

const m = (art: number) => ({ art });

export const KINDS: Kind[] = [
  {
    id: 'portfolio',
    name: 'Portfolio',
    emoji: '✦',
    content: {
      kind: 'portfolio',
      brand: 'Asha Rao',
      mark: 'AR',
      eyebrow: 'Product designer · Bengaluru',
      headline: 'I design *calm* software for busy people.',
      lede: 'Eight years shaping apps used by millions — from the first sketch to the last shipped pixel. Taking on two new projects this spring.',
      primary: { label: 'See my work', href: '#work' },
      secondary: { label: 'Get in touch', href: '#contact' },
      navCta: { label: 'Say hello', href: '#contact' },
      heroMedia: m(8),
      sections: [
        { id: 'numbers', type: 'stats', items: [{ value: '8+', label: 'years designing' }, { value: '40', label: 'products shipped' }, { value: '12M', label: 'people using them' }, { value: '3', label: 'design awards' }] },
        {
          id: 'work', nav: 'Work', type: 'cards', eyebrow: 'Selected work', title: 'Things I have *shaped*', intro: 'A few favourites from the last few years.', showMedia: true,
          items: [
            { title: 'Ledger', text: 'A calmer banking app for first-time earners.', meta: '2025 · Fintech', media: m(1) },
            { title: 'Monsoon', text: 'A weather app that tells you what to wear.', meta: '2024 · Consumer', media: m(5) },
            { title: 'Tide', text: 'A booking flow that cut drop-offs by 38%.', meta: '2024 · Travel', media: m(11) },
            { title: 'Loom & Leaf', text: 'Brand and online store for a handloom label.', meta: '2023 · Commerce', media: m(6) },
          ],
        },
        { id: 'about', nav: 'About', type: 'about', eyebrow: 'About', title: 'Hi, I am Asha.', text: 'I started as an illustrator, fell in love with systems and never looked back. I care about the small moments — the empty state, the error message, the way a button feels under your thumb.', points: ['Product & interaction design', 'Design systems', 'Prototyping in code', 'Workshops & mentoring'], media: m(2) },
        { id: 'experience', nav: 'Experience', type: 'list', eyebrow: 'Experience', title: 'Where I have worked', items: [{ meta: '2022 — Now', title: 'Lead designer, Oak Labs', text: 'Leading a team of six across web and mobile.', aside: 'Bengaluru' }, { meta: '2019 — 2022', title: 'Senior designer, Kite', text: 'Built the design system from scratch.', aside: 'Remote' }, { meta: '2017 — 2019', title: 'Designer, Northwind', text: 'Websites and brands for 30+ clients.', aside: 'Mumbai' }] },
        { id: 'kind-words', type: 'quote', text: 'Asha does not just design screens — she changes how a whole team thinks about people.', name: 'Rohan Mehta', role: 'CEO, Oak Labs' },
        { id: 'contact', nav: 'Contact', type: 'contact', eyebrow: 'Contact', title: 'Let us make something *good*.', text: 'Tell me about your project. I reply within a day.', email: 'hello@asharao.design', cta: 'Email me' },
      ],
      socials: [{ label: 'Dribbble', href: 'https://dribbble.com/' }, { label: 'LinkedIn', href: 'https://www.linkedin.com/' }, { label: 'Instagram', href: 'https://www.instagram.com/' }],
      footer: '© 2026 Asha Rao',
    },
  },
  {
    id: 'developer',
    name: 'Developer',
    emoji: '⌘',
    content: {
      kind: 'developer',
      brand: 'Kabir Sen',
      mark: 'KS',
      eyebrow: 'Full-stack developer · Pune',
      headline: 'I build *fast*, friendly things for the web.',
      lede: 'TypeScript, Go and Postgres by day, open source by night. I turn fuzzy ideas into products people actually use.',
      primary: { label: 'View projects', href: '#projects' },
      secondary: { label: 'Read my CV', href: '#experience' },
      navCta: { label: 'Hire me', href: '#contact' },
      heroMedia: m(3),
      sections: [
        {
          id: 'projects', nav: 'Projects', type: 'cards', eyebrow: 'Projects', title: 'Things I have *built*', intro: 'Open source, side projects and a few things I am proud of.', showMedia: true,
          items: [
            { title: 'Tern', text: 'A tiny, reliable job queue for Postgres.', meta: 'Go · 2.1k stars', media: m(9) },
            { title: 'Pocket CI', text: 'Run your whole CI pipeline on a laptop.', meta: 'Rust · CLI', media: m(4) },
            { title: 'Paperplane', text: 'Newsletters with Markdown and zero tracking.', meta: 'TypeScript · SaaS', media: m(7) },
            { title: 'Hoot', text: 'Real-time polls for classrooms of 500.', meta: 'Elixir · Realtime', media: m(12) },
          ],
        },
        { id: 'numbers', type: 'stats', items: [{ value: '7', label: 'years shipping' }, { value: '120+', label: 'open-source PRs' }, { value: '2.1k', label: 'GitHub stars' }, { value: '99.99%', label: 'uptime kept' }] },
        { id: 'experience', nav: 'Experience', type: 'list', eyebrow: 'Experience', title: 'Where I have *shipped*', items: [{ meta: '2023 — Now', title: 'Senior engineer, Relay', text: 'Payments infrastructure handling ₹900 crore a month.', aside: 'Remote' }, { meta: '2020 — 2023', title: 'Engineer, Swiftcart', text: 'Rebuilt checkout; page loads went from 4s to 0.9s.', aside: 'Pune' }, { meta: '2018 — 2020', title: 'Developer, Freelance', text: 'Twenty-odd websites for small businesses.', aside: 'Everywhere' }] },
        { id: 'about', nav: 'About', type: 'about', eyebrow: 'About', title: 'Boring tech, *exciting* results.', text: 'I like small teams, clear tickets and code that the next person can read. When I am not coding I am probably cycling up a hill or losing at chess.', points: ['TypeScript & React', 'Go & Postgres', 'System design', 'Performance'], media: m(10) },
        { id: 'contact', nav: 'Contact', type: 'contact', eyebrow: 'Contact', title: 'Have a hard problem?', text: 'I am open to full-time roles and interesting contracts.', email: 'kabir@kabirsen.dev', cta: 'Send an email' },
      ],
      socials: [{ label: 'GitHub', href: 'https://github.com/' }, { label: 'LinkedIn', href: 'https://www.linkedin.com/' }, { label: 'X', href: 'https://x.com/' }],
      footer: '© 2026 Kabir Sen',
    },
  },
  {
    id: 'startup',
    name: 'Startup',
    emoji: '◆',
    content: {
      kind: 'startup',
      brand: 'Tidy',
      mark: 'T',
      eyebrow: 'New · Tidy 2.0 is here',
      headline: 'Your inbox, *finally* under control.',
      lede: 'Tidy sorts, snoozes and bundles email so you spend minutes, not hours. Works with Gmail and Outlook in two clicks.',
      primary: { label: 'Start free', href: '#pricing' },
      secondary: { label: 'How it works', href: '#features' },
      navCta: { label: 'Get Tidy', href: '#pricing' },
      heroMedia: m(8),
      sections: [
        { id: 'numbers', type: 'stats', items: [{ value: '40k', label: 'teams on Tidy' }, { value: '11 min', label: 'saved per day' }, { value: '4.9★', label: 'average rating' }, { value: '2M', label: 'emails sorted daily' }] },
        {
          id: 'features', nav: 'Features', type: 'cards', eyebrow: 'Features', title: 'Less email. *More* day.', intro: 'Everything you need to reach inbox zero — and stay there.', showMedia: true,
          items: [
            { title: 'Smart sort', text: 'Newsletters, receipts and people — each in its own lane.', media: m(9) },
            { title: 'Snooze', text: 'Hide a thread until the moment it matters.', media: m(12) },
            { title: 'One-click unsubscribe', text: 'Clear years of junk in a single afternoon.', media: m(6) },
            { title: 'Focus hours', text: 'Batch delivery so email stops interrupting you.', media: m(3) },
            { title: 'Shared inbox', text: 'Assign, comment and close — no more cc chains.', media: m(4) },
            { title: 'Private by design', text: 'Your email never leaves your device unencrypted.', media: m(10) },
          ],
        },
        { id: 'pricing', nav: 'Pricing', type: 'list', eyebrow: 'Pricing', title: 'Simple, *honest* pricing', intro: 'Every plan includes a 30-day free trial.', items: [{ meta: 'Free', title: 'Personal', text: 'One inbox, smart sort and snooze.', aside: '$0' }, { meta: 'Most popular', title: 'Pro', text: 'Unlimited inboxes, focus hours, priority support.', aside: '$8 / mo' }, { meta: 'For teams', title: 'Team', text: 'Shared inboxes, roles and admin controls.', aside: '$14 / user' }] },
        { id: 'love', type: 'quote', text: 'I went from 4,000 unread emails to zero in a week. Tidy gave me my mornings back.', name: 'Farah Khan', role: 'Founder, Brightside' },
        { id: 'about', nav: 'About', type: 'about', eyebrow: 'Why Tidy', title: 'Built by people who *hated* email.', text: 'We are a team of twelve in Bengaluru and Berlin. We do not sell data, we do not show ads, and we answer every support email ourselves.', points: ['No ads, ever', 'Data stays yours', 'Humans on support', 'Cancel any time'], media: m(1) },
        { id: 'faq', nav: 'FAQ', type: 'faq', eyebrow: 'Questions', title: 'Good to *know*', items: [{ q: 'Does Tidy read my email?', a: 'Sorting happens on your device. We never read, sell or train anything on your messages.' }, { q: 'Which email accounts work?', a: 'Gmail, Google Workspace, Outlook and any IMAP inbox.' }, { q: 'Can I cancel any time?', a: 'Yes — one click in settings, and you keep your data.' }, { q: 'Is there a student discount?', a: 'Pro is *free* for students and teachers. Just use your school email.' }] },
        { id: 'contact', nav: 'Contact', type: 'contact', eyebrow: 'Get started', title: 'Try Tidy *free* for 30 days.', text: 'No card needed. Set up takes under two minutes.', email: 'hello@tidy.app', cta: 'Start your trial' },
      ],
      socials: [{ label: 'X', href: 'https://x.com/' }, { label: 'LinkedIn', href: 'https://www.linkedin.com/' }, { label: 'YouTube', href: 'https://www.youtube.com/' }],
      footer: '© 2026 Tidy Labs Pvt. Ltd.',
    },
  },
  {
    id: 'restaurant',
    name: 'Restaurant',
    emoji: '◐',
    content: {
      kind: 'restaurant',
      brand: 'Masala & Co.',
      mark: 'M&',
      eyebrow: 'Home-style kitchen · Hyderabad',
      headline: 'Slow-cooked food, *served* with love.',
      lede: 'Recipes from our grandmothers, spices ground every morning and a table that is always waiting for you.',
      primary: { label: 'See the menu', href: '#menu' },
      secondary: { label: 'Book a table', href: '#visit' },
      navCta: { label: 'Book a table', href: '#visit' },
      heroMedia: m(7),
      sections: [
        {
          id: 'menu', nav: 'Menu', type: 'cards', eyebrow: 'The menu', title: 'Our *favourites*', intro: 'Cooked fresh every day. Ask us about today’s specials.', showMedia: false,
          items: [
            { title: 'Hyderabadi Dum Biryani', text: 'Aged basmati, slow-cooked with tender mutton and saffron.', price: '₹340', media: m(1) },
            { title: 'Paneer Butter Masala', text: 'Soft paneer in a smoky tomato and cashew gravy.', price: '₹280', media: m(2) },
            { title: 'Mirchi ka Salan', text: 'Green chillies in a tangy peanut and sesame curry.', price: '₹180', media: m(3) },
            { title: 'Kheema Pav', text: 'Spiced minced lamb with butter-toasted buns.', price: '₹220', media: m(4) },
            { title: 'Double ka Meetha', text: 'Bread pudding with cardamom, saffron and nuts.', price: '₹140', media: m(5) },
            { title: 'Irani Chai', text: 'Slow-brewed, creamy and served with Osmania biscuits.', price: '₹40', media: m(6) },
          ],
        },
        { id: 'story', nav: 'Story', type: 'about', eyebrow: 'Our story', title: 'Since 1998, *one* kitchen.', text: 'What started as a six-table room above a spice shop is now a neighbourhood favourite. The recipes have not changed. Neither has the chai.', points: ['Spices ground daily', 'No preservatives', 'Family recipes', 'Vegetarian friendly'], media: m(11) },
        { id: 'kitchen', type: 'gallery', eyebrow: 'From the kitchen', title: 'Made by *hand*', items: [{ caption: 'Morning spice grind', media: m(5) }, { caption: 'Dum, sealed for hours', media: m(1) }, { caption: 'The chai counter', media: m(12) }, { caption: 'Sunday lunch', media: m(8) }, { caption: 'Fresh from the tandoor', media: m(7) }, { caption: 'Sweets for the road', media: m(9) }] },
        { id: 'visit', nav: 'Visit', type: 'list', eyebrow: 'Visit us', title: 'Opening *hours*', items: [{ meta: 'Mon — Fri', title: 'Lunch & dinner', text: 'Kitchen closes at 10:30 PM.', aside: '12 PM — 11 PM' }, { meta: 'Sat — Sun', title: 'All day', text: 'Breakfast from 9 AM on weekends.', aside: '9 AM — 11:30 PM' }, { meta: 'Festivals', title: 'Special hours', text: 'Call us to check before you come.', aside: 'Varies' }] },
        { id: 'review', type: 'quote', text: 'The biryani tastes exactly like my grandmother’s. I have been coming every Sunday for ten years.', name: 'Sameer Ali', role: 'Regular since 2015' },
        { id: 'contact', nav: 'Contact', type: 'contact', eyebrow: 'Reservations', title: 'Save me a *seat*.', text: 'Walk-ins welcome. For groups of six or more, please book ahead.', email: 'table@masalaandco.in', phone: '+91 98765 43210', address: '14 Road No. 2, Banjara Hills, Hyderabad', cta: 'Book by email' },
      ],
      socials: [{ label: 'Instagram', href: 'https://www.instagram.com/' }, { label: 'Zomato', href: 'https://www.zomato.com/' }, { label: 'Google Maps', href: 'https://maps.google.com/' }],
      footer: '© 2026 Masala & Co.',
    },
  },
  {
    id: 'studio',
    name: 'Studio',
    emoji: '▲',
    content: {
      kind: 'studio',
      brand: 'Northwind Studio',
      mark: 'N',
      eyebrow: 'Brand & digital studio · Mumbai',
      headline: 'We make brands people *remember*.',
      lede: 'Strategy, identity and websites for companies that would rather be loved than merely noticed.',
      primary: { label: 'See our work', href: '#work' },
      secondary: { label: 'What we do', href: '#services' },
      navCta: { label: 'Start a project', href: '#contact' },
      heroMedia: m(5),
      sections: [
        { id: 'numbers', type: 'stats', items: [{ value: '14', label: 'years in business' }, { value: '200+', label: 'brands launched' }, { value: '18', label: 'people, one room' }, { value: '9', label: 'awards (we do not count)' }] },
        {
          id: 'work', nav: 'Work', type: 'cards', eyebrow: 'Case studies', title: 'Recent *work*', intro: 'A few projects we are still talking about.', showMedia: true,
          items: [
            { title: 'Chaayos Reserve', text: 'A premium tea brand, from name to packaging.', meta: 'Identity · Packaging', media: m(2) },
            { title: 'Metro Bikes', text: 'Wayfinding and an app for 4,000 shared bikes.', meta: 'Product · Signage', media: m(4) },
            { title: 'Saathi', text: 'A warmer website for an elder-care network.', meta: 'Website · Content', media: m(8) },
            { title: 'Kora Denim', text: 'A campaign that sold out the first drop in a day.', meta: 'Campaign', media: m(6) },
          ],
        },
        { id: 'services', nav: 'Services', type: 'list', eyebrow: 'Services', title: 'What we *do*', items: [{ meta: '01', title: 'Brand strategy', text: 'Positioning, naming and the story you tell.', aside: '4–6 weeks' }, { meta: '02', title: 'Visual identity', text: 'Logos, type, colour and a system that scales.', aside: '6–8 weeks' }, { meta: '03', title: 'Websites', text: 'Designed and built to be fast and easy to edit.', aside: '8–12 weeks' }, { meta: '04', title: 'Campaigns', text: 'Launches, films and everything in between.', aside: 'Ongoing' }] },
        { id: 'about', nav: 'Studio', type: 'about', eyebrow: 'The studio', title: 'Small team. *Big* care.', text: 'Every project is led by a partner from the first call to launch day. No hand-offs, no junior bait-and-switch.', points: ['Partner-led projects', 'Fixed, clear quotes', 'In-house developers', 'Work in English or Hindi'], media: m(9) },
        { id: 'client', type: 'quote', text: 'Northwind understood our brand better than we did. Sales doubled in the year after launch.', name: 'Ira Kapoor', role: 'CMO, Chaayos' },
        { id: 'contact', nav: 'Contact', type: 'contact', eyebrow: 'New projects', title: 'Got a brand to *build*?', text: 'Tell us where you are and where you want to be. We will reply within two working days.', email: 'hello@northwind.studio', phone: '+91 22 4000 1234', cta: 'Start a project' },
      ],
      socials: [{ label: 'Instagram', href: 'https://www.instagram.com/' }, { label: 'Behance', href: 'https://www.behance.net/' }, { label: 'LinkedIn', href: 'https://www.linkedin.com/' }],
      footer: '© 2026 Northwind Studio LLP',
    },
  },
  {
    id: 'photographer',
    name: 'Photographer',
    emoji: '◉',
    content: {
      kind: 'photographer',
      brand: 'Meera Iyer',
      mark: 'MI',
      eyebrow: 'Photographer · Goa',
      headline: 'Quiet light, *honest* moments.',
      lede: 'Portraits, weddings and travel stories — shot slowly, edited gently, delivered with care.',
      primary: { label: 'View gallery', href: '#gallery' },
      secondary: { label: 'Packages', href: '#packages' },
      navCta: { label: 'Book a shoot', href: '#contact' },
      heroMedia: m(7),
      sections: [
        { id: 'gallery', nav: 'Gallery', type: 'gallery', eyebrow: 'Recent work', title: 'Selected *frames*', items: [{ caption: 'Monsoon, Palolem', media: m(7) }, { caption: 'Anjali, portrait', media: m(8) }, { caption: 'Fontainhas at noon', media: m(1) }, { caption: 'The last ferry', media: m(11) }, { caption: 'Haldi morning', media: m(5) }, { caption: 'Salt pans, Ribandar', media: m(2) }, { caption: 'Night market', media: m(12) }, { caption: 'A quiet vow', media: m(9) }, { caption: 'Fishermen, dawn', media: m(6) }] },
        { id: 'about', nav: 'About', type: 'about', eyebrow: 'About', title: 'I photograph *people*, not poses.', text: 'Ten years, four hundred shoots and one rule: make people comfortable, and the pictures take care of themselves. I shoot mostly on location with natural light.', points: ['Natural light', 'Small, relaxed shoots', 'Full gallery in 2 weeks', 'Printed albums'], media: m(8) },
        { id: 'packages', nav: 'Packages', type: 'list', eyebrow: 'Packages', title: 'Ways to *work* together', items: [{ meta: '1 hour', title: 'Portraits', text: 'One location, 40 edited photos.', aside: '₹15,000' }, { meta: 'Half day', title: 'Stories', text: 'Families, couples or your small business.', aside: '₹32,000' }, { meta: 'Full day', title: 'Weddings', text: 'Two photographers, 600+ photos and an album.', aside: 'from ₹1,20,000' }] },
        { id: 'kind-words', type: 'quote', text: 'We forgot the camera was even there. Every photo feels like a memory, not a pose.', name: 'Rhea & Dev', role: 'Married in Goa, 2025' },
        { id: 'contact', nav: 'Contact', type: 'contact', eyebrow: 'Bookings', title: 'Let us make some *memories*.', text: 'Share your date and a little about you. I take on a limited number of shoots each month.', email: 'hello@meeraiyer.photo', phone: '+91 91234 56780', cta: 'Check my dates' },
      ],
      socials: [{ label: 'Instagram', href: 'https://www.instagram.com/' }, { label: 'Pinterest', href: 'https://www.pinterest.com/' }],
      footer: '© 2026 Meera Iyer Photography',
    },
  },
  {
    id: 'writer',
    name: 'Writer',
    emoji: '¶',
    content: {
      kind: 'writer',
      brand: 'The Slow Letter',
      mark: 'SL',
      eyebrow: 'A newsletter by Nisha Varma',
      headline: 'Essays on living *well* with less.',
      lede: 'One thoughtful letter every Sunday about time, money, food and the art of doing fewer things better. Read by 18,000 people.',
      primary: { label: 'Subscribe free', href: '#contact' },
      secondary: { label: 'Read the essays', href: '#essays' },
      navCta: { label: 'Subscribe', href: '#contact' },
      heroMedia: m(2),
      sections: [
        {
          id: 'essays', nav: 'Essays', type: 'cards', eyebrow: 'Latest', title: 'Recent *essays*', intro: 'New letters every Sunday morning.', showMedia: true,
          items: [
            { title: 'The joy of a boring week', text: 'Why an uneventful calendar might be the richest thing you own.', meta: '6 min read · Sep 2026', media: m(11) },
            { title: 'Cooking for one', text: 'Small rituals that turned my weeknight dinners into the best part of the day.', meta: '8 min read · Aug 2026', media: m(1) },
            { title: 'A year without buying clothes', text: 'What I missed, what I did not, and what I learned about wanting.', meta: '11 min read · Jul 2026', media: m(6) },
            { title: 'Letters to my younger self', text: 'Money advice I wish I had taken at twenty-two.', meta: '5 min read · Jun 2026', media: m(10) },
          ],
        },
        { id: 'numbers', type: 'stats', items: [{ value: '18k', label: 'readers every week' }, { value: '212', label: 'letters sent' }, { value: '61%', label: 'open rate' }, { value: '0', label: 'ads, ever' }] },
        { id: 'about', nav: 'About', type: 'about', eyebrow: 'The writer', title: 'Hello, I am *Nisha*.', text: 'I left a busy job in advertising to write about slowing down. I live in Kochi with too many books and one opinionated cat.', points: ['Weekly, every Sunday', 'Free forever', 'No spam, no ads', 'Unsubscribe in one click'], media: m(8) },
        { id: 'reader', type: 'quote', text: 'The only email I actually look forward to. It feels like a letter from a wise friend.', name: 'Anand R.', role: 'Reader since 2022' },
        { id: 'contact', nav: 'Subscribe', type: 'contact', eyebrow: 'Subscribe', title: 'Get the letter on *Sunday*.', text: 'Join 18,000 readers. One email a week, nothing else.', email: 'letters@theslowletter.com', cta: 'Subscribe by email' },
      ],
      socials: [{ label: 'Substack', href: 'https://substack.com/' }, { label: 'Instagram', href: 'https://www.instagram.com/' }, { label: 'RSS', href: '#' }],
      footer: '© 2026 Nisha Varma',
    },
  },
  {
    id: 'wedding',
    name: 'Wedding',
    emoji: '♡',
    content: {
      kind: 'wedding',
      brand: 'Priya & Arjun',
      mark: 'P&A',
      eyebrow: '12 · 12 · 2026 · Udaipur',
      headline: 'We are getting *married*!',
      lede: 'Three days of colour, music and far too much food by the lake. We would love for you to be there.',
      primary: { label: 'RSVP', href: '#contact' },
      secondary: { label: 'The plan', href: '#schedule' },
      navCta: { label: 'RSVP', href: '#contact' },
      heroMedia: m(2),
      sections: [
        { id: 'schedule', nav: 'Schedule', type: 'list', eyebrow: 'The plan', title: 'Three *days* of joy', items: [{ meta: 'Dec 11 · 6 PM', title: 'Mehendi & music', text: 'Henna, snacks and an open mic for brave cousins.', aside: 'Lakeside Terrace' }, { meta: 'Dec 12 · 11 AM', title: 'The wedding', text: 'Pheras under the old banyan tree.', aside: 'Garden Court' }, { meta: 'Dec 12 · 8 PM', title: 'Sangeet & dinner', text: 'Dance first, eat later. Or both at once.', aside: 'Palace Hall' }, { meta: 'Dec 13 · 10 AM', title: 'Farewell brunch', text: 'Chai, jalebi and slow goodbyes.', aside: 'Courtyard' }] },
        { id: 'story', nav: 'Our story', type: 'about', eyebrow: 'Our story', title: 'It started with a *wrong* number.', text: 'Arjun called Priya by mistake in 2019 looking for a plumber. They talked for three hours. Seven years, two cities and one very patient dog later — here we are.', points: ['Met in 2019', 'Engaged in Coorg', 'One dog, named Biscuit', 'Zero plumbers hired'], media: m(8) },
        {
          id: 'travel', nav: 'Travel', type: 'cards', eyebrow: 'Getting there', title: 'Travel & *stay*', intro: 'We have held rooms for guests — mention our names when you book.', showMedia: true,
          items: [
            { title: 'The Lake Palace', text: 'Where we are staying. Ten minutes by boat to every event.', meta: 'Hotel · Special rate', media: m(11) },
            { title: 'Haveli Guest House', text: 'Cosy rooms in the old city, walking distance to the ghats.', meta: 'Guest house', media: m(6) },
            { title: 'From the airport', text: 'Free shuttles on Dec 10 and 11, every two hours.', meta: 'Maharana Pratap Airport', media: m(4) },
          ],
        },
        { id: 'moments', type: 'gallery', eyebrow: 'Moments', title: 'A few of our *favourites*', items: [{ caption: 'First trip, Pondicherry', media: m(1) }, { caption: 'Biscuit joins the family', media: m(5) }, { caption: 'The proposal', media: m(9) }, { caption: 'Diwali 2025', media: m(12) }] },
        { id: 'faq', nav: 'FAQ', type: 'faq', eyebrow: 'Questions', title: 'The *little* things', items: [{ q: 'What should I wear?', a: 'Bright colours for Mehendi, traditional for the wedding, dancing shoes for the Sangeet.' }, { q: 'Can I bring a plus-one?', a: 'If your invite says so — we are counting every jalebi.' }, { q: 'Are kids welcome?', a: 'Absolutely. There is a kids’ corner with games every evening.' }, { q: 'Gifts?', a: 'Your presence is the gift. Truly.' }] },
        { id: 'contact', nav: 'RSVP', type: 'contact', eyebrow: 'RSVP', title: 'Will you *join* us?', text: 'Please reply by 1 November so we can plan food for everyone (and extra jalebi).', email: 'rsvp@priyaandarjun.in', cta: 'RSVP by email' },
      ],
      socials: [{ label: 'Photos', href: '#moments' }, { label: 'Map', href: 'https://maps.google.com/' }],
      footer: 'Made with love by Priya & Arjun',
    },
  },
  {
    id: 'shop',
    name: 'Shop',
    emoji: '◍',
    content: {
      kind: 'shop',
      brand: 'Clay & Co.',
      mark: 'C&',
      eyebrow: 'Handmade ceramics · Auroville',
      headline: 'Everyday pottery, *made* by hand.',
      lede: 'Mugs, bowls and vases thrown on our wheel, glazed in small batches and made to be used every single day.',
      primary: { label: 'Shop the collection', href: '#shop' },
      secondary: { label: 'Visit the studio', href: '#studio' },
      navCta: { label: 'Shop now', href: '#shop' },
      heroMedia: m(10),
      sections: [
        {
          id: 'shop', nav: 'Shop', type: 'cards', eyebrow: 'The collection', title: 'Fresh from the *kiln*', intro: 'Every piece is one of a kind — glazes vary a little, and that is the point.', showMedia: true,
          items: [
            { title: 'Morning Mug', text: 'Holds 350 ml. Fits two hands on cold days.', price: '₹890', media: m(10) },
            { title: 'Serving Bowl', text: 'Wide and shallow for dal, salads and sharing.', price: '₹1,450', media: m(2) },
            { title: 'Bud Vase', text: 'For one flower, or a sprig from the garden.', price: '₹650', media: m(12) },
            { title: 'Dinner Plates, set of 4', text: 'Matte outside, glossy inside, dishwasher safe.', price: '₹2,400', media: m(3) },
          ],
        },
        { id: 'numbers', type: 'stats', items: [{ value: '1,200', label: 'pieces a year' }, { value: '3', label: 'potters' }, { value: '100%', label: 'lead-free glazes' }, { value: '48h', label: 'dispatch' }] },
        { id: 'studio', nav: 'Studio', type: 'about', eyebrow: 'The studio', title: 'Mud, fire and *patience*.', text: 'We are three potters in a small studio surrounded by cashew trees. Every piece is thrown, trimmed, glazed and fired by hand — which takes about three weeks.', points: ['Local clay', 'Lead-free glazes', 'Plastic-free packing', 'Studio visits on Saturdays'], media: m(5) },
        { id: 'care', nav: 'Shipping', type: 'list', eyebrow: 'Good to know', title: 'Care & *shipping*', items: [{ meta: 'Shipping', title: 'Across India', text: 'Packed in paper and straw. Delivered in 3–6 days.', aside: 'Free over ₹2,000' }, { meta: 'Care', title: 'Made for daily use', text: 'Microwave and dishwasher safe unless noted.', aside: 'Handle with love' }, { meta: 'Returns', title: 'Broken in transit?', text: 'Send a photo and we will send a new one.', aside: 'Always' }] },
        { id: 'review', type: 'quote', text: 'My chai tastes better in this mug. I cannot explain it, but I have bought four more.', name: 'Lakshmi N.', role: 'Customer in Chennai' },
        { id: 'faq', nav: 'FAQ', type: 'faq', eyebrow: 'Questions', title: 'Asked *often*', items: [{ q: 'Is every piece exactly like the photo?', a: 'No two pieces match — the glaze moves in the kiln. That is the charm.' }, { q: 'Do you ship abroad?', a: 'Yes, to most countries. Shipping is calculated at checkout.' }, { q: 'Can I visit the studio?', a: 'Saturdays from 10 AM. Come watch the wheel spin.' }, { q: 'Do you take custom orders?', a: 'Yes — cafés, weddings and gifts. Email us your idea.' }] },
        { id: 'contact', nav: 'Contact', type: 'contact', eyebrow: 'Say hello', title: 'Custom orders *welcome*.', text: 'Cafés, weddings and gifts — tell us what you need and we will throw it.', email: 'studio@clayandco.in', address: 'Aspiration Road, Auroville, Tamil Nadu', cta: 'Email the studio' },
      ],
      socials: [{ label: 'Instagram', href: 'https://www.instagram.com/' }, { label: 'Etsy', href: 'https://www.etsy.com/' }],
      footer: '© 2026 Clay & Co.',
    },
  },
  {
    id: 'clinic',
    name: 'Clinic',
    emoji: '✚',
    content: {
      kind: 'clinic',
      brand: 'Sunrise Clinic',
      mark: 'S',
      eyebrow: 'Family health · Chennai',
      headline: 'Care that *listens* first.',
      lede: 'Unhurried appointments, clear answers and doctors who remember your name. Open seven days a week.',
      primary: { label: 'Book an appointment', href: '#contact' },
      secondary: { label: 'Our services', href: '#services' },
      navCta: { label: 'Book now', href: '#contact' },
      heroMedia: m(12),
      sections: [
        {
          id: 'services', nav: 'Services', type: 'cards', eyebrow: 'Services', title: 'How we can *help*', intro: 'Everything your family needs, under one roof.', showMedia: false,
          items: [
            { title: 'General check-ups', text: 'Thorough, 30-minute visits for all ages.', meta: 'Walk-in or booked', media: m(1) },
            { title: 'Children’s health', text: 'Vaccinations, growth checks and gentle care.', meta: 'Paediatrics', media: m(2) },
            { title: 'Women’s health', text: 'Screenings and advice in a private, calm setting.', meta: 'Gynaecology', media: m(3) },
            { title: 'Diabetes care', text: 'Plans, tests and diet support that fit real life.', meta: 'Chronic care', media: m(4) },
            { title: 'Physiotherapy', text: 'Back, knee and sports injuries — with home exercises.', meta: 'Rehab', media: m(5) },
            { title: 'Lab tests', text: 'Most reports on the same day, on your phone.', meta: 'Diagnostics', media: m(6) },
          ],
        },
        { id: 'numbers', type: 'stats', items: [{ value: '25', label: 'years caring' }, { value: '9', label: 'specialists' }, { value: '7 days', label: 'a week' }, { value: '4.8★', label: 'patient rating' }] },
        { id: 'doctors', nav: 'Doctors', type: 'list', eyebrow: 'Our doctors', title: 'People you can *trust*', items: [{ meta: 'MBBS, MD', title: 'Dr. Anjali Rao', text: 'General physician. 20 years of family practice.', aside: 'Mon — Sat' }, { meta: 'MBBS, DCH', title: 'Dr. Vikram Suresh', text: 'Paediatrician. Loved by kids, trusted by parents.', aside: 'Mon — Fri' }, { meta: 'MBBS, MS', title: 'Dr. Fatima Sheikh', text: 'Gynaecologist with a focus on preventive care.', aside: 'Tue — Sun' }] },
        { id: 'about', nav: 'About', type: 'about', eyebrow: 'About us', title: 'A clinic that feels like *home*.', text: 'Sunrise began as a single doctor’s room in 2001. Today we are a team of nine specialists — and we still keep appointments long enough to actually talk.', points: ['No rushed visits', 'Reports on your phone', 'Wheelchair accessible', 'Insurance accepted'], media: m(8) },
        { id: 'patient', type: 'quote', text: 'For the first time a doctor explained everything slowly, and drew me a picture. I finally understood my own health.', name: 'Mrs. Kamala V.', role: 'Patient since 2010' },
        { id: 'faq', nav: 'FAQ', type: 'faq', eyebrow: 'Questions', title: 'Before you *visit*', items: [{ q: 'Do I need an appointment?', a: 'Walk-ins are welcome. Booking ahead means a shorter wait.' }, { q: 'Do you accept insurance?', a: 'Yes, all major insurers. Bring your card and a photo ID.' }, { q: 'Can I get reports online?', a: 'Most lab reports reach your phone the same day.' }, { q: 'Is there parking?', a: 'Free parking for patients behind the clinic.' }] },
        { id: 'contact', nav: 'Contact', type: 'contact', eyebrow: 'Appointments', title: 'We are here *every* day.', text: 'Call, email or walk in. Emergencies are seen straight away.', email: 'care@sunriseclinic.in', phone: '+91 44 2345 6789', address: '22 Luz Church Road, Mylapore, Chennai', cta: 'Email for a booking' },
      ],
      socials: [{ label: 'Google Maps', href: 'https://maps.google.com/' }, { label: 'Facebook', href: 'https://www.facebook.com/' }],
      footer: '© 2026 Sunrise Family Clinic',
    },
  },
  {
    id: 'coach',
    name: 'Coach',
    emoji: '▶',
    content: {
      kind: 'coach',
      brand: 'Strong with Sana',
      mark: 'SS',
      eyebrow: 'Strength coach · Delhi',
      headline: 'Get strong. Stay *consistent*.',
      lede: 'Simple strength programs for busy people. Three short sessions a week, real coaching and zero shame.',
      primary: { label: 'Find your program', href: '#programs' },
      secondary: { label: 'Results', href: '#results' },
      navCta: { label: 'Join now', href: '#contact' },
      heroMedia: m(4),
      sections: [
        { id: 'results', nav: 'Results', type: 'stats', items: [{ value: '1,800', label: 'people coached' }, { value: '92%', label: 'still training at 6 months' }, { value: '3×', label: 'sessions a week' }, { value: '45 min', label: 'per session' }] },
        {
          id: 'programs', nav: 'Programs', type: 'cards', eyebrow: 'Programs', title: 'Pick your *starting* line', intro: 'Every program adapts to your equipment, schedule and injuries.', showMedia: true,
          items: [
            { title: 'First Steps', text: 'Never lifted before? Start here with bodyweight and bands.', meta: '8 weeks · Beginner', media: m(4) },
            { title: 'Strong Foundations', text: 'Learn the big lifts with feedback on every video you send.', meta: '12 weeks · Intermediate', media: m(9) },
            { title: 'Home Hero', text: 'A pair of dumbbells, a mat and a plan that works.', meta: '10 weeks · Any level', media: m(3) },
          ],
        },
        { id: 'pricing', nav: 'Pricing', type: 'list', eyebrow: 'Coaching', title: 'Ways to *train* with me', items: [{ meta: 'Self-guided', title: 'App only', text: 'Your program, tracking and video library.', aside: '₹999 / mo' }, { meta: 'Most popular', title: 'Coached', text: 'Weekly check-ins and form reviews on video.', aside: '₹3,499 / mo' }, { meta: 'One to one', title: 'In person', text: 'Two sessions a week in South Delhi.', aside: '₹12,000 / mo' }] },
        { id: 'about', nav: 'About', type: 'about', eyebrow: 'Your coach', title: 'Hi, I am *Sana*.', text: 'I was the kid who skipped PE. At 28 I walked into a gym terrified — now I help people like my old self feel at home under a barbell.', points: ['Certified strength coach', 'Pre & post-natal trained', 'Injury-aware programming', 'Hindi and English'], media: m(8) },
        { id: 'client', type: 'quote', text: 'I deadlifted my body weight at 52. My kids think I am a superhero now. So do I.', name: 'Rekha Malhotra', role: 'Coached for 1 year' },
        { id: 'faq', nav: 'FAQ', type: 'faq', eyebrow: 'Questions', title: 'You might be *wondering*', items: [{ q: 'I have never lifted. Is that okay?', a: 'That is exactly who First Steps is for. We start with bodyweight.' }, { q: 'Do I need a gym?', a: 'No. Home Hero works with two dumbbells and a mat.' }, { q: 'What if I miss a week?', a: 'Life happens. Your plan adjusts — no guilt, no restart.' }, { q: 'Can I train with an injury?', a: 'Tell me about it first. I adapt every program to your body.' }] },
        { id: 'contact', nav: 'Contact', type: 'contact', eyebrow: 'Start today', title: 'Your first week is *free*.', text: 'Tell me a little about your goals and I will build your first week myself.', email: 'coach@strongwithsana.in', cta: 'Start my free week' },
      ],
      socials: [{ label: 'Instagram', href: 'https://www.instagram.com/' }, { label: 'YouTube', href: 'https://www.youtube.com/' }],
      footer: '© 2026 Strong with Sana',
    },
  },
  {
    id: 'band',
    name: 'Band',
    emoji: '♪',
    content: {
      kind: 'band',
      brand: 'The Monsoon Club',
      mark: 'MC',
      eyebrow: 'Indie band · Kolkata',
      headline: 'Songs for *long*, rainy drives.',
      lede: 'Four friends, one old Maruti van and a new album called “Petrichor”. Out everywhere now.',
      primary: { label: 'Listen now', href: '#music' },
      secondary: { label: 'Tour dates', href: '#tour' },
      navCta: { label: 'Tickets', href: '#tour' },
      heroMedia: m(11),
      sections: [
        {
          id: 'music', nav: 'Music', type: 'cards', eyebrow: 'Music', title: 'Our *records*', intro: 'Streaming everywhere. Vinyl at every show.', showMedia: true,
          items: [
            { title: 'Petrichor', text: 'Our second album. Ten songs about rain and leaving home.', meta: 'Album · 2026', media: m(11) },
            { title: 'Howrah at 2 AM', text: 'The single that started it all, now with strings.', meta: 'Single · 2025', media: m(12) },
            { title: 'Paper Boats', text: 'Our first EP, recorded in a bedroom in Salt Lake.', meta: 'EP · 2023', media: m(7) },
          ],
        },
        { id: 'tour', nav: 'Tour', type: 'list', eyebrow: 'On tour', title: 'Come say *hi*', items: [{ meta: 'Oct 18', title: 'Kolkata — Harbour Hall', text: 'Album launch night with special guests.', aside: 'Sold out' }, { meta: 'Oct 25', title: 'Bengaluru — The Loft', aside: 'Tickets' }, { meta: 'Nov 02', title: 'Mumbai — Blue Room', aside: 'Tickets' }, { meta: 'Nov 09', title: 'Delhi — Garden Stage', aside: 'Few left' }] },
        { id: 'about', nav: 'Band', type: 'about', eyebrow: 'The band', title: 'Four friends, *one* van.', text: 'We met at college, started playing at friends’ weddings and never quite stopped. Our songs are about the small, soggy, beautiful parts of city life.', points: ['Riya — vocals', 'Arnab — guitar', 'Tenzing — bass', 'Joy — drums'], media: m(6) },
        { id: 'press', type: 'quote', text: 'The warmest record of the year. It sounds like chai on a verandah while the monsoon goes wild.', name: 'Rolling Pages', role: 'Album review' },
        { id: 'contact', nav: 'Contact', type: 'contact', eyebrow: 'Booking', title: 'Want us at your *festival*?', text: 'For shows, collaborations and press, drop us a line.', email: 'hello@monsoonclub.in', cta: 'Email the band' },
      ],
      socials: [{ label: 'Spotify', href: 'https://open.spotify.com/' }, { label: 'Instagram', href: 'https://www.instagram.com/' }, { label: 'YouTube', href: 'https://www.youtube.com/' }],
      footer: '© 2026 The Monsoon Club',
    },
  },
];

export const kindById = (id: string) => KINDS.find((k) => k.id === id) ?? KINDS[0];
export const kindIndex = (id: string) => Math.max(0, KINDS.findIndex((k) => k.id === id));
